config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from mainapp.views import errors_handlers

from config import settings

urlpatterns = [
    path('administrations_section/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path("social_auth/", include("social_django.urls", namespace="social")),
]

handler500 = errors_handlers.handler500

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp.views import *
from mainapp.apps import MainappConfig


app_name = MainappConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('rules_regulations', RulesRegulationsView.as_view(), name='rules_regulations'),
    path('contacts/', ContactsPageView.as_view(), name='contacts'),
    path('doc_site/', DocPageView.as_view(), name='doc_site'),
    #path('login/', LoginPageView.as_view(), name='login'),

    path(
        'courses/',
        (CoursesListView.as_view()),
        name='courses'
    ),
    path(
        'courses/<int:pk>/detail',
        CoursesDetailView.as_view(),
        name='course_detail'
    ),
    path(
        'course/feedback/',
        CourseFeedbackProcessFormView.as_view(),
        name='course_feedback'
    ),

    # CURD для новостей
    path('news/', NewsListView.as_view(), name='news'),
    path(
        'news/create',
        NewsCreateView.as_view(),
        name='news_create'
    ),
    path(
        'news/<int:pk>/detail',
        NewsDetailView.as_view(),
        name='news_detail'
    ),
    path(
        'news/<int:pk>/update',
        NewsUpdateView.as_view(),
        name='news_update'
    ),
    path(
        'news/<int:pk>/delete',
        NewsDeleteView.as_view(),
        name='news_delete'
    ),

    # Фича редиректа на гугл
    path('google_redirect/<str:param>', redirect_page, name='google_redirect'),

    path('log_view/<int:tail>', LogView.as_view(), name='log_view'),
    path('log_download', LogDownloadView.as_view(), name='log_download'),
]

mainapp/models/course_feedback.py
__all__ = ['RatingChoices', 'CourseFeedback']

from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _


class RatingChoices(models.IntegerChoices):
    ONE = (1, '⭐')
    TWO = (2, '⭐⭐')
    THREE = (3, '⭐⭐⭐')
    FOUR = (4, '⭐⭐⭐⭐')
    FIVE = (5, '⭐⭐⭐⭐⭐')


class CourseFeedback(models.Model):
    course = models.ForeignKey('mainapp.Courses', on_delete=models.DO_NOTHING, verbose_name=_("Course"))
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("User"))
    feedback = models.TextField(default=_("No feedback"), verbose_name=_("Feedback"))

    rating = models.SmallIntegerField(
        choices=RatingChoices.choices,
        default=RatingChoices.FIVE,
        verbose_name=_("Rating")
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.course}: {self.user}|{self.rating}"

    class Meta:
        verbose_name = _("CourseFeedback")
        verbose_name_plural = _("CourseFeedbacks")

mainapp/models/courses.py
__all__ = ['Courses']

from django.db import models
from django.utils.translation import gettext_lazy as _
from mainapp.models.managers import CoursesManager


class Courses(models.Model):
    objects = CoursesManager()

    name = models.CharField(max_length=255, verbose_name='Name')
    description = models.TextField(verbose_name='Description', null=True, blank=True)
    description_as_md = models.BooleanField(verbose_name='As markdown', default=False)

    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Cost', default=0)

    image = models.CharField(max_length=25, default='not_found.gif', verbose_name='Image')

    created = models.DateTimeField(auto_now_add=True, verbose_name='Created', editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name='Edited', editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.name}'

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")

mainapp/models/lessons.py
__all__ = ['Lessons']

from django.db import models

from django.utils.translation import gettext_lazy as _


class Lessons(models.Model):
    course = models.ForeignKey('mainapp.Courses', on_delete=models.CASCADE)
    number = models.PositiveIntegerField(verbose_name='Lesson number')
    title = models.CharField(max_length=150, verbose_name='Name')
    description = models.TextField(verbose_name='Description', null=True, blank=True)

    description_as_md = models.BooleanField(verbose_name='As markdown', default=False)

    created = models.DateTimeField(auto_now_add=True, verbose_name='Created', editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name='Edited', editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.pk} {self.title}'

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("Lesson")
        verbose_name_plural = _("Lessons")

mainapp/models/news.py
__all__ = ['News']

from django.db import models
from django.utils.translation import gettext_lazy as _


class News(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    description = models.CharField(max_length=300, verbose_name='Preview', null=True, blank=True)
    author = models.CharField(max_length=70, verbose_name='Author', null=True, blank=True)
    content = models.TextField(verbose_name='Content', blank=True, null=True)
    content_as_md = models.BooleanField(default=False, verbose_name='As markdown')
    url = models.CharField(max_length=350, verbose_name='Source', default='No url provided', null=True, blank=True)
    source = models.CharField(
        max_length=55, verbose_name='Source name', default='unknown_source', null=True, blank=True
    )

    image_url = models.CharField(max_length=250, default='not_found.svg', verbose_name='Image', null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True, verbose_name='Created', editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name='Edited', editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.title[:25]}...'

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("News")
        ordering = ('-created', )

mainapp/models/teachers.py
__all__ = ['TeachersCourse']

from django.db import models
from django.utils.translation import gettext_lazy as _


class TeachersCourse(models.Model):
    course = models.ManyToManyField('mainapp.Courses')

    name_first = models.CharField(max_length=100, verbose_name='Name')
    name_second = models.CharField(max_length=100, verbose_name='Surname')
    birthday = models.DateField(verbose_name='Birthday')

    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.pk:>03} {self.name_first} {self.name_second}'

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")
        # ordering = ('-name_first', )

mainapp/forms/feedback_form.py
__all__ = ['CourseFeedbackForm']

from django import forms

from mainapp import models as mainapp_m
from mainapp.models import RatingChoices


class CourseFeedbackForm(forms.ModelForm):

    def __init__(self, *args, course=None, user=None, **kwargs):
        ret = super().__init__(*args, **kwargs)
        if ret:
            for i in ret:
                print(i)
        if course and user:
            self.fields["course"].initial = course.pk
            self.fields["user"].initial = user.pk
        return ret

    class Meta:
        model = mainapp_m.CourseFeedback
        fields = ("course", "user", "feedback", "rating")
        widgets = {
            "course": forms.HiddenInput(),
            "user": forms.HiddenInput(),
            "rating": forms.RadioSelect(choices=RatingChoices.choices)
        }

mainapp/forms/mail_feedback_form.py
__all__ = ['MailFeedbackForm']

from django import forms
from django.utils.translation import gettext_lazy as _


class MailFeedbackForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput)
    message = forms.CharField(
        widget=forms.Textarea,
        help_text=_("Enter your message"),
        label=_("Message"),
    )

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields["user_id"].initial = user.pk

mainapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from mainapp.utils.get_news_api import get_news


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'special_data': "don't tell anyone!"})
        return context


class NewsPageView(TemplateView):
    template_name = "mainapp/news.html"

    def get_context_data(self, page=1, **kwargs):
        context = super().get_context_data(**kwargs)

        ## TODO MOVE PAGINATION LOGICS TO PAGINATOR CLASS IF POSSIBLE
        all_news = get_news()
        pages_total = len(all_news) // 5

        page = pages_total if page > pages_total else page

        next_page, prev_page = None, None

        if page - 1 > 0:
            start_range = page - 1
            prev_page = page - 1
        else:
            start_range = page

        if page + 1 < pages_total:
            end_range = page + 2
            next_page = page + 1
        else:
            end_range = pages_total

        all_news = all_news[page * 5 - 5: page * 5]

        context.update({
            "news": all_news,
            "total_range": range(start_range, end_range),
            "page": page,
            "next": next_page,
            "prev": prev_page,
        })

        return context


class CoursesPageView(TemplateView):
    template_name = 'mainapp/courses_list.html'


class ContactsPageView(TemplateView):
    template_name = 'mainapp/contacts.html'


class LoginPageView(TemplateView):
    template_name = 'mainapp/login.html'


class DocPageView(TemplateView):
    template_name = 'mainapp/doc_site.html'


def redirect_page(request, param: str):
    return redirect(to=f'https://google.com/search?q={param}')

mainapp/views/errors_handlers.py
__all__ = ("handler500", )

from django.shortcuts import render


def handler500(request, *args, **kwargs):
    return render(request, '500.html', status=500)

mainapp/templates/mainapp/courses/courses_detail.html
{% extends 'base.html' %}
{% load static markdownify crispy_forms_tags cache %}

<!-- Title -->
{% block title %}
    {{ course_object.name }}
{% endblock title %}

<!-- Content -->
{% block content %}
    <h1 class="mt-2">
        {{ course_object.name }}
    </h1>
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-6 col-lg-8 order-2 order-md-1">
            <div class="row h-100">
                <div class="col-12">
                {% if course_object.description_as_md %}
                    {{ course_object.description|markdownify }}
                {% else %}
                    {{ course_object.description }}
                {% endif %}
            </div>
            <!-- Teachers. Fix sie of header -->
            <div class="col-12 align-self-end">
                <p>
                    <h5 class="text-muted">Преподаватели:</h5>
                    {% for item in teachers %}
                        {{ item.name_second }} {{ item.name_first }}{% if forloop.last %}{% else %},{% endif %}
                    {% endfor %}
                </p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4 order-1 order-md-2">
            <div class="row h-100">
                <div class="col-12 align-self-start">
                <img class="w-100" src="{% static course_object.image %}">
                </div>
                <div class="col-12 align-self-end d-none d-md-block">
                    <p class="text-center mt-2">
                        <small class="text-uppercase">цена</small><br>
                        <span style="font-size: 30pt;">{{ course_object.cost}}</span><br>
                        <a href="#" class="btn btn-outline-primary btn-block"
                           role="button">Купить</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="accordion" id="accordionLessons">
    <!-- Тоже можно вынести в отдельный инклюд -->
    {% cache 300 lessons %}
        {% for item in lessons %}
            <div class="card">
                <div class="card-header" id="headLessonPk{{ item.pk }}">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left" type="button"
                        data-toggle="collapse" data-target="#collapse{{ item.pk }}"
                        aria-expanded="true" aria-controls="collapse{{ item.pk }}">
                            {{ item.course.name }} - {{ item.title }}
                        </button>
                    </h2>
                </div>

                <div id="collapse{{ item.pk }}" class="collapse"
                    aria-labelledby="headLessonPk{{ item.pk }}"
                    data-parent="#accordionLessons">
                    <div class="card-body">
                        <div class="row justify-content-center">
                            <div class="col-12 text-center">
                                <img class="img-thumbnail float-left" src="{% static 'img/not_found.gif' %}" width="150px">
                            </div>
                            <div class="col-12">
                                {% if item.description_as_md %}
                                    {{ item.description|markdownify }}
                                {% else %}
                                    {{ item.description }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endcache %}
    <h3>Отзывы</h3>

<div id="feedback_list">
    {% if feedback_list %}
        {% for item in feedback_list %}
            {% include 'mainapp/courses/includes/feedback_card.html' %}
        {% endfor %}
    {% else %}
        <p>No feedback yet. Be first!</p>
    {% endif %}
</div>

{% if feedback_form %}
    <div class="card" id="cardForm">
        <div class="card-body">
            <h5 class="card-title">Добавить отзыв</h5>
            <h6 class="card-subtitle mb-2 text-muted">Вы ещё не оставляли отзыв к этому курсу</h6>
            <p class="card-text">
                <form action="{% url 'mainapp:course_feedback' %}" method="POST" id="feedbackForm">
                    {% csrf_token %}
                    {{ feedback_form|crispy }}
                </form>
                <button id="feedbackSubmit" class="btn btn-primary btn-block">Отправить</button>
            </p>
        </div>
    </div>
{% endif %}

{% endblock content %}

{% block js %}
    {% if feedback_form %}
        <script>
            $(document).ready(function () {
                $("#feedbackSubmit").click(function () {

                    $("#cardForm").hide();

                    let $form = $("#feedbackForm");
                    $.ajax({
                        type: "POST",
                        url: $form.attr("action"),
                        data: $form.serialize(),
                        success: function (data) {
                            $("#feedback_list").append(data.card);
                        }
                    });
                });
            });
        </script>
    {% endif %}
{% endblock js %}

mainapp/templates/mainapp/courses/courses_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Курсы
{% endblock title %}

{% block content %}
    <div class="row justify-content-center mt-3">
        {% for item in object_list %}
            {% include 'mainapp/courses/includes/course_list_item.html' with course=item %}
        {% endfor %}
    </div>
        {% include 'includes/pagination.html' %}
{% endblock content %}