authapp/urls.py
from django.urls import path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile_edit/<int:pk>/", views.ProfileEditView.as_view(), name="profile_edit"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from mainapp.views import errors_handlers

from config import settings

urlpatterns = [
    path('administrations_section/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path("social_auth/", include("social_django.urls", namespace="social")),
]

handler500 = errors_handlers.handler500

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp.views import *
from mainapp.apps import MainappConfig


app_name = MainappConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('rules_regulations', RulesRegulationsView.as_view(), name='rules_regulations'),
    path('contacts/', ContactsPageView.as_view(), name='contacts'),
    path('doc_site/', DocPageView.as_view(), name='doc_site'),
    #path('login/', LoginPageView.as_view(), name='login'),

    path(
        'courses/',
        (CoursesListView.as_view()),
        name='courses'
    ),
    path(
        'courses/<int:pk>/detail',
        CoursesDetailView.as_view(),
        name='course_detail'
    ),
    path(
        'course/feedback/',
        CourseFeedbackProcessFormView.as_view(),
        name='course_feedback'
    ),

    # CURD для новостей
    path('news/', NewsListView.as_view(), name='news'),
    path(
        'news/create',
        NewsCreateView.as_view(),
        name='news_create'
    ),
    path(
        'news/<int:pk>/detail',
        NewsDetailView.as_view(),
        name='news_detail'
    ),
    path(
        'news/<int:pk>/update',
        NewsUpdateView.as_view(),
        name='news_update'
    ),
    path(
        'news/<int:pk>/delete',
        NewsDeleteView.as_view(),
        name='news_delete'
    ),

    # Фича редиректа на гугл
    path('google_redirect/<str:param>', redirect_page, name='google_redirect'),

    path('log_view/<int:tail>', LogView.as_view(), name='log_view'),
    path('log_download', LogDownloadView.as_view(), name='log_download'),
]

templates/includes/footer.html
{% load static i18n %}


<div class="container-lg mt-auto">
        <hr>
        <div class="row justify-content-center">
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Braniac</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="{% url 'mainapp:index' %}">{% translate "HomePage" %}</a></li>
                    <li><a href="{% url 'mainapp:news' %}">{% translate "News" %}</a></li>
                    <li><a href="{% url 'authapp:login' %}">{% translate "Enter" %}</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>{% transalte "UsefullLinks" %}</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="{% url 'mainapp:rules_regulations' %}">{% translate "TermsConditions" %}</a></li>
                    <li><a href="{% url 'mainapp:rules_regulations' %}">{% translate "PrivacyCookies" %}</a></li>
                    <li><a href="#">{% translate "APIDocs" %}</a></li>
                    <li><a href="{% url 'mainapp:doc_site' %}">{% translate "Documentation" %}</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>{% translate "WeAtSocials" %}</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
                </div>
                </p>
                <p>
                    <strong>{% translate "OurApp" %}</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
                </div>
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div>
                <p><small>&copy; GeekBrains 2022</small></p>
            </div>
        </div>
    </div>

    <!-- /Footer -->
    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>


    <!-- Toasts --> {# Че это?! #}
    <script>
        $(document).ready(function () {

            {% if messages %}
                // Toasts
                $(".toast").toast({ delay: 5000 });
                $(".toast").toast("show");
            {% endif %}
        });
    </script>

templates/includes/menu.html
{% load static i18n %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">
                <img src="/static/img/logo.png" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:news' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'mainapp:news' %}">{% translate "News" %}</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:courses' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'mainapp:courses' %}">{% translate "Courses" %}</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="ddProfile"
                               role="button" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">
                                {% translate "Profile" %}
                            </a>

                                <div class="dropdown-menu" aria-labelledby="ddProfile">
                                    <a class="dropdown-item" href="{% url 'authapp:profile_edit' pk=request.user.pk %}">{% translate "Edit profile" %}</a>
                                    <a class="dropdown-item" href="#">{% translate "My Courses" %}</a>
                                    {% if user.is_staff %}
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">{% translate "Moderation" %}</a>
                                        {% if user.is_superuser %}
                                            <a class="dropdown-item" href="{% url 'admin:index' %}"
                                               target="_blank">{% translate "Admin section" %}</a>
                                            <a class="dropdown-item"
                                               href="{% url 'mainapp:log_view' tail=1 %}">{% translate "Logs" %}</a>
                                        {% endif %}
                                    {% endif %}
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'authapp:logout' %}">{% translate "Exit" %}</a>
                                </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authapp:login' %}">{% translate "Enter" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.view_name == 'authapp:register' %}active{% endif %}"
                               href="{% url 'authapp:register' %}">{% translate "Register" %}</a>
                        </li>
                    {% endif %}
                    <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:contacts' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'mainapp:contacts' %}">{% translate "Contacts" %}</a>
                    </li>
                </ul>
                <div class="row justify-content-end m-0">
                    <div class="col p-0 border-right">
                        <form action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input name="language" type="hidden" value="ru">
                            <button type="submit" class="btn btn-link">🇷🇺</button>
                        </form>
                    </div>
                    <div class="col p-0 border-left">
                        <form action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input name="language" type="hidden" value="en">
                            <button type="submit" class="btn btn-link">🇬🇧</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
</nav>

templates/includes/messages.html
<div class="position-absolute w-100" style="z-index: 1;">
  <div aria-live="polite" aria-atomic="true" class="m-2">
    <!-- Position it -->
    <div class="d-flex align-items-end flex-column">
        {% for message in messages %}
            <!-- Then put toasts within -->
            <div class="toast flex-fill w-100 {% if message.level == 30 %} border-warning {% endif %}
                " role="alert" aria-live="assertive" aria-atomic="true"
                style="right: 0;">
                <div class="toast-header">
                    <span class="mr-2"><i class="far fa-envelope"></i></span>
                    <strong class="mr-auto {% if message.level == 30 %}text-warning{% endif %}">
                        {{ message.tags|capfirst }} message
                    </strong>
                    <small class="text-muted">just now</small>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    {{ message }}
                </div>
            </div>
            {% if message.level >= 20 %}
                <!-- If message will dissapere you will find message in console -->
                <script>
                    console.log("{{ message }}");
                </script>
            {% endif %}

        {% endfor %}

    </div>

  </div>
</div>

templates/includes/pagination.html
{% load paginate_correct_page %}

{% if page_obj.has_other_pages %}
    <div class="row justify-content-center align-items-center mt-3 mb-n3">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.dateFrom %}&dateFrom={{ request.GET.dateFrom }}{% endif %}{% if request.GET.dateTo %}&dateTo={{ request.GET.dateTo }}{% endif %}">Previous</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.dateFrom %}&dateFrom={{ request.GET.dateFrom }}{% endif %}{% if request.GET.dateTo %}&dateTo={{ request.GET.dateTo }}{% endif %}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}
                <li class="page-item active"><a class="page-link" >
                    {{ page_obj.number }}
                </a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.dateFrom %}&dateFrom={{ request.GET.dateFrom }}{% endif %}{% if request.GET.dateTo %}&dateTo={{ request.GET.dateTo }}{% endif %}">{{ page_obj.next_page_number }}</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.dateFrom %}&dateFrom={{ request.GET.dateFrom }}{% endif %}{% if request.GET.dateTo %}&dateTo={{ request.GET.dateTo }}{% endif %}">Next</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endif %}