config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from mainapp.views import errors_handlers

from config import settings

urlpatterns = [
    path('administrations_section/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path("social_auth/", include("social_django.urls", namespace="social")),
]

handler500 = errors_handlers.handler500

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp.views import *
from mainapp.apps import MainappConfig


app_name = MainappConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('rules_regulations', RulesRegulationsView.as_view(), name='rules_regulations'),
    path('contacts/', ContactsPageView.as_view(), name='contacts'),
    path('doc_site/', DocPageView.as_view(), name='doc_site'),
    #path('login/', LoginPageView.as_view(), name='login'),

    path(
        'courses/',
        (CoursesListView.as_view()),
        name='courses'
    ),
    path(
        'courses/<int:pk>/detail',
        CoursesDetailView.as_view(),
        name='course_detail'
    ),
    path(
        'course/feedback/',
        CourseFeedbackProcessFormView.as_view(),
        name='course_feedback'
    ),

    # CURD для новостей
    path('news/', NewsListView.as_view(), name='news'),
    path(
        'news/create',
        NewsCreateView.as_view(),
        name='news_create'
    ),
    path(
        'news/<int:pk>/detail',
        NewsDetailView.as_view(),
        name='news_detail'
    ),
    path(
        'news/<int:pk>/update',
        NewsUpdateView.as_view(),
        name='news_update'
    ),
    path(
        'news/<int:pk>/delete',
        NewsDeleteView.as_view(),
        name='news_delete'
    ),

    # Фича редиректа на гугл
    path('google_redirect/<str:param>', redirect_page, name='google_redirect'),

    path('log_view/<int:tail>', LogView.as_view(), name='log_view'),
    path('log_download', LogDownloadView.as_view(), name='log_download'),
]

mainapp/models/course_feedback.py
__all__ = ['RatingChoices', 'CourseFeedback']

from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _


class RatingChoices(models.IntegerChoices):
    ONE = (1, '⭐')
    TWO = (2, '⭐⭐')
    THREE = (3, '⭐⭐⭐')
    FOUR = (4, '⭐⭐⭐⭐')
    FIVE = (5, '⭐⭐⭐⭐⭐')


class CourseFeedback(models.Model):
    course = models.ForeignKey('mainapp.Courses', on_delete=models.DO_NOTHING, verbose_name=_("Course"))
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("User"))
    feedback = models.TextField(default=_("No feedback"), verbose_name=_("Feedback"))

    rating = models.SmallIntegerField(
        choices=RatingChoices.choices,
        default=RatingChoices.FIVE,
        verbose_name=_("Rating")
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.course}: {self.user}|{self.rating}"

    class Meta:
        verbose_name = _("CourseFeedback")
        verbose_name_plural = _("CourseFeedbacks")

mainapp/models/courses.py
__all__ = ['Courses']

from django.db import models
from django.utils.translation import gettext_lazy as _
from mainapp.models.managers import CoursesManager


class Courses(models.Model):
    objects = CoursesManager()

    name = models.CharField(max_length=255, verbose_name='Name')
    description = models.TextField(verbose_name='Description', null=True, blank=True)
    description_as_md = models.BooleanField(verbose_name='As markdown', default=False)

    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Cost', default=0)

    image = models.CharField(max_length=25, default='not_found.gif', verbose_name='Image')

    created = models.DateTimeField(auto_now_add=True, verbose_name='Created', editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name='Edited', editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.name}'

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")

mainapp/models/lessons.py
__all__ = ['Lessons']

from django.db import models

from django.utils.translation import gettext_lazy as _


class Lessons(models.Model):
    course = models.ForeignKey('mainapp.Courses', on_delete=models.CASCADE)
    number = models.PositiveIntegerField(verbose_name='Lesson number')
    title = models.CharField(max_length=150, verbose_name='Name')
    description = models.TextField(verbose_name='Description', null=True, blank=True)

    description_as_md = models.BooleanField(verbose_name='As markdown', default=False)

    created = models.DateTimeField(auto_now_add=True, verbose_name='Created', editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name='Edited', editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.pk} {self.title}'

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("Lesson")
        verbose_name_plural = _("Lessons")

mainapp/models/news.py
__all__ = ['News']

from django.db import models
from django.utils.translation import gettext_lazy as _


class News(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    description = models.CharField(max_length=300, verbose_name='Preview', null=True, blank=True)
    author = models.CharField(max_length=70, verbose_name='Author', null=True, blank=True)
    content = models.TextField(verbose_name='Content', blank=True, null=True)
    content_as_md = models.BooleanField(default=False, verbose_name='As markdown')
    url = models.CharField(max_length=350, verbose_name='Source', default='No url provided', null=True, blank=True)
    source = models.CharField(
        max_length=55, verbose_name='Source name', default='unknown_source', null=True, blank=True
    )

    image_url = models.CharField(max_length=250, default='not_found.svg', verbose_name='Image', null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True, verbose_name='Created', editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name='Edited', editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.title[:25]}...'

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("News")
        ordering = ('-created', )

mainapp/models/teachers.py
__all__ = ['TeachersCourse']

from django.db import models
from django.utils.translation import gettext_lazy as _


class TeachersCourse(models.Model):
    course = models.ManyToManyField('mainapp.Courses')

    name_first = models.CharField(max_length=100, verbose_name='Name')
    name_second = models.CharField(max_length=100, verbose_name='Surname')
    birthday = models.DateField(verbose_name='Birthday')

    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.pk:>03} {self.name_first} {self.name_second}'

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")
        # ordering = ('-name_first', )

mainapp/forms/feedback_form.py
__all__ = ['CourseFeedbackForm']

from django import forms

from mainapp import models as mainapp_m
from mainapp.models import RatingChoices


class CourseFeedbackForm(forms.ModelForm):

    def __init__(self, *args, course=None, user=None, **kwargs):
        ret = super().__init__(*args, **kwargs)
        if ret:
            for i in ret:
                print(i)
        if course and user:
            self.fields["course"].initial = course.pk
            self.fields["user"].initial = user.pk
        return ret

    class Meta:
        model = mainapp_m.CourseFeedback
        fields = ("course", "user", "feedback", "rating")
        widgets = {
            "course": forms.HiddenInput(),
            "user": forms.HiddenInput(),
            "rating": forms.RadioSelect(choices=RatingChoices.choices)
        }

mainapp/forms/mail_feedback_form.py
__all__ = ['MailFeedbackForm']

from django import forms
from django.utils.translation import gettext_lazy as _


class MailFeedbackForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput)
    message = forms.CharField(
        widget=forms.Textarea,
        help_text=_("Enter your message"),
        label=_("Message"),
    )

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields["user_id"].initial = user.pk

authapp/views/login.py
__all__ = ['CustomLoginView']

from django.contrib import messages
from django.contrib.auth.views import LoginView

from django.utils.safestring import mark_safe               # was ist das?
from django.utils.translation import gettext_lazy as _      # translation


class CustomLoginView(LoginView):

    def form_valid(self, form):
        ret = super().form_valid(form)
        username = self.request.user.get_full_name() \
            if self.request.user.get_full_name() \
            else self.request.user.get_username()
        message = _(f"Login success!<br>Hi, %{username}")
        messages.add_message(self.request, messages.INFO, mark_safe(message))
        return ret

    def form_invalid(self, form):
        for _unused, msg in form.error_messages.items():
            messages.add_message(
                self.request,
                messages.WARNING,
                mark_safe(f"Something goes very wrong:<br>{msg}"),
            )
        return self.render_to_response(self.get_context_data(form=form))

mainapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from mainapp.utils.get_news_api import get_news


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'special_data': "don't tell anyone!"})
        return context


class NewsPageView(TemplateView):
    template_name = "mainapp/news.html"

    def get_context_data(self, page=1, **kwargs):
        context = super().get_context_data(**kwargs)

        ## TODO MOVE PAGINATION LOGICS TO PAGINATOR CLASS IF POSSIBLE
        all_news = get_news()
        pages_total = len(all_news) // 5

        page = pages_total if page > pages_total else page

        next_page, prev_page = None, None

        if page - 1 > 0:
            start_range = page - 1
            prev_page = page - 1
        else:
            start_range = page

        if page + 1 < pages_total:
            end_range = page + 2
            next_page = page + 1
        else:
            end_range = pages_total

        all_news = all_news[page * 5 - 5: page * 5]

        context.update({
            "news": all_news,
            "total_range": range(start_range, end_range),
            "page": page,
            "next": next_page,
            "prev": prev_page,
        })

        return context


class CoursesPageView(TemplateView):
    template_name = 'mainapp/courses_list.html'


class ContactsPageView(TemplateView):
    template_name = 'mainapp/contacts.html'


class LoginPageView(TemplateView):
    template_name = 'mainapp/login.html'


class DocPageView(TemplateView):
    template_name = 'mainapp/doc_site.html'


def redirect_page(request, param: str):
    return redirect(to=f'https://google.com/search?q={param}')

mainapp/views/errors_handlers.py
__all__ = ("handler500", )

from django.shortcuts import render


def handler500(request, *args, **kwargs):
    return render(request, '500.html', status=500)

mainapp/templates/mainapp/contacts.html
{% extends 'base.html' %}
{% load static mailto crispy_forms_tags i18n %}


{% block content %}
<div class="container-md">
    <p>
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">{% translate "Contacts" %}</h1>
            <p class="lead">{% translate "ContactUsPlease" %}</p> {# Обязательно свяжитесь с нами! Ваш комфорт - наша забота. #}
            </div>
        </div>
    </p>
<p>

<div class="row justify-content-around mt-n2">

    <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
        <div class="card h-100 shadow">
            <div class="card-body">
                <div style="position:relative;overflow:hidden;"><a                 href="https://yandex.ru/maps/org/petropavlovskaya_krepost/146720535721/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:0px;">{% translate "PetroPavlFort" %}</a><a                 href="https://yandex.ru/maps/2/saint-petersburg/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:14px;">Достопримечательность в                 Санкт‑Петербурге</a><a                 href="https://yandex.ru/maps/2/saint-petersburg/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:28px;">Музей в Санкт‑Петербурге</a><iframe                 src="https://yandex.ru/map-widget/v1/-/CCUAZHcrhA" width="100%" height="300" frameborder="0"                 allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>             </div>
                    <h5 class="card-title">{% translate "SaintP" %}</h5>
                <p class="card-text">
                    <ul class="list-unstyled">
                        <li>{% translate "Phone" %}</li>
                        <li><strong>+7-999-11-11111</strong></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>Email</li>
                        <li><strong>{{  'geeklab@spb.ru'|mailto }}</strong></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>{% translate "Address" %}</li>
                        <li><strong>{% translate "PetroPavlFortAddr" %}</strong></li>
                    </ul>
                </p>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
        <div class="card h-100 shadow">
            <div class="card-body">
                <div style="position:relative;overflow:hidden;"><a                 href="https://yandex.ru/maps/org/kazanskiy_kreml/95813866834/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:0px;">{% translate "KazanKremlin" %}</a><a                 href="https://yandex.ru/maps/43/kazan/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей в Казани</a><a                 href="https://yandex.ru/maps/43/kazan/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:28px;">Достопримечательность в Казани</a><iframe                 src="https://yandex.ru/map-widget/v1/-/CCUAZHX3xB" width="100%" height="300" frameborder="0"                 allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>             </div>
                <h5 class="card-title">{% translate "Kazan" %}</h5>
                <p class="card-text">
                    <ul class="list-unstyled">
                        <li>{% translate "Phone" %}</li>
                        <li><strong>+7-999-22-22222</strong></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>Email</li>
                        <li><strong>{{ 'geeklab@kz.ru'|mailto }}</strong></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>{% translate "Address" %}</li>
                        <li><strong>{% trans "KazanKremlAddr" %}</strong></li>
                    </ul>
                </p>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
        <div class="card h-100 shadow">
            <div class="card-body">
                <div style="position:relative;overflow:hidden;"><a                 href="https://yandex.ru/maps/org/sobor_pokrova_presvyatoy_bogoroditsy_na_rvu/175159255687/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:0px;">Собор Покрова Пресвятой Богородицы на                 Рву</a><a href="https://yandex.ru/maps/213/moscow/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"                 style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей в Москве</a><iframe                 src="https://yandex.ru/map-widget/v1/-/CCUAZHh9kD" width="100%" height="300" frameborder="0"                 allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>             </div>
                    <h5 class="card-title">{% translate "Moscow" %}</h5>
                    <p class="card-text">
                    <ul class="list-unstyled">
                        <li>{% translate "Phone" %}</li>
                        <li><strong>+7-999-33-33333</strong></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>Email</li>
                        <li><strong>{{ 'geeklab@msk.ru'|mailto }}</strong></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>{% translate "Address" %}</li>
                        <li><strong>{% translate "MoscowAddr" %}</strong></li>
                    </ul>
                </p>
            </div>
        </div>
    </div>

</div>
</div>

</p>
{% if form %}
    <p>
        <h3>{% translate "ContactTechSUpportViaEm" %}{#  #}</h3>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary btn-block">
                {% translate "Send" %}
            </button>
        </form>
    </p>
{% endif %}

{% endblock content %}

mainapp/templates/mainapp/doc_site.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container-md">

        
<div class="row justify-content-center align-items-center mt-3">
  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Документация по сайту
      </div>
      <div class="card-body">

        <h5 class="card-title">CSS-стили</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/" target="_blank">Bootstrap
              v4.6</a></li>
          <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
        </ul>
        </p>

        <h5 class="card-title">Иконки</h5>
        <p class="card-text">
          <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">FontAwesome 5.15.3</a>
        </p>

        <h5 class="card-title">Графики</h5>
        <p class="card-text">
          <a href="https://www.chartjs.org/">ChartJS</a>
        </p>

        <h5 class="card-title">Графика</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">Логотип by
              flamingtext.com</a></li>
          <li><a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">Фотографии by
              pexels.com</a>. Все изображения распространяются под бесплатной лицензией. Для страницы обзоров фотографии
            должны быть с соотношением сторон кратным 2.912 (например, 1920x659)</li>
          <li><a href="https://getavataaars.com/" target="_blank" rel="noopener noreferrer">Аватарки пользователей by
              getavataaars.com</a></li>
        </ul>
        </p>

      </div>
    </div>
  </div>
</div>


    </div>


{% endblock content %}

mainapp/templates/mainapp/index.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% translate "WelcomeLanding" %}{% endblock title %}
{% block content %}
    <div class="container-md">


    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" style="background-color: #777; font-size: 1.25rem;">
            <div class="carousel-item active">
                <img src="{% static 'img/slider001.jpg' %}" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>{% translate "BeProactive" %}</h3>
                    <p>{% translate "StudyTrends" %}</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/slider002.jpg' %}" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>{% translate "StudyAnywhere" %}</h3>
                    <p>{% translate "ParkLibraryWarmBlanket" %}</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/slider003.jpg' %}" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>{% translate "BraniacIsUs" %}</h3>
                    <p>{% translate "JoinOurTeam" %}</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="jumbotron">
        <h1 class="display-4">{% translate "GreetingsHeader" %}</h1>
        <p class="lead">
            {% translate "GreetingMessage" %}
        </p>
    </div>

    <h3>{% translate "MembersFeedback" %}</h3>

    <div class="row text-center">

        <div class="col-lg-4">
            <img src="{% static 'img/user001.png' %}" alt="..." style="max-width: 140px;">
            <h2>{% translate "Lera" %}</h2>
            <p>{% translate "LeraFeed" %}</p>
        </div>

        <div class="col-lg-4">
            <img src="{% static 'img/user002.png' %}" alt="..." style="max-width: 140px;">
            <h2>{% translate "Anthony" %}</h2>
            <p>{% translate "AnthonyFeed" %}</p>
        </div>

        <div class="col-lg-4">
            <img src="{% static 'img/user003.png' %}" alt="..." style="max-width: 140px;">
            <h2>{% translate "Leonard" %}</h2>
            <p>{% translate "LeonardFeed" %}</p>
        </div>

        <div class="col-lg-4">
            <img src="{% static 'img/user004.png' %}" alt="..." style="max-width: 140px;">
            <h2>{% translate "Venia" %}</h2>
            <p>{% translate "VeniaFeed" %}</p>
        </div>


    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-7">
            <h1>{% translate "HundredsOfCourses" %}</h1>
            <p>{% translate "HundredsOfCourseDesc" %}</p>
        </div>
        <div class="col-md-5">
            <img src="{% static 'img/promo001.jpg' %}" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-5">
            <img src="{% static 'img/promo002.jpg' %}" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
        <div class="col-md-7">
            <h1>{% translate "TurnKnowledgeToGold" %}</h1>
            <p>{% translate "TurnKnowDesc" %}</p>
        </div>
    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-7">
            <h1>{% translate "StrongUnited" %}</h1>
            <p>{% translate "StrongUnitedDesc" %}</p>
        </div>
        <div class="col-md-5">
            <img src="{% static 'img/promo003.jpg' %}" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
    </div>


    </div>


{% endblock content %}

mainapp/templates/mainapp/log_view.html
{% extends 'base.html' %}

{% block content %}

    <div class="row justify-content-end my-2">
        <div class="col-sm-4 col-lg-2">
            <a href="{% url 'mainapp:log_download' %}" class="btn btn-primary btn-block" role="button">
                Скачать
            </a>
        </div>
        <a href="{% url 'mainapp:log_view' tail=1 %}" class="btn btn-success btn-sm">TAIL</a>
        <a href="{% url 'mainapp:log_view' tail=0 %}" class="btn btn-success btn-sm">HEAD</a>
    </div>
    <p>
        <div class="text-center text-muted">
            <small>{% if request.resolver_match.kwargs.tail == 0 %}First{% else %}Last{% endif %} 1000 lines of log file</small>
        </div>
        <pre>{{ log }}</pre>
    </p>

{% endblock content %}

mainapp/templates/mainapp/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
  <div class="text-center">
    <p>
      <a href="/static"><img src="{% static 'img/logo.png' %}" alt=""></a>
    </p>
    <h2>Вход пользователя</h2>
    <form>
      <p>
        <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя"
          required="" autofocus="">
      </p>
      <p>
        <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль" required="">
      </p>
      <p>
        <button type="submit" class="btn btn-primary btn-block">Войти</button>
      </p>
    </form>
    <p class="text-right">
      <a href=""><small>Забыли пароль?</small></a>
    </p>
    <h4>Вход через социальные сети</h4>
    <p>
    <div class="btn-group btn-block" role="group">
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-github"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
    </div>
    </p>
  </div>
</div>


{% endblock content %}

mainapp/templates/mainapp/rules_and_regulations.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "RegulationsTitle" %}{% endblock %}

{% block content %}
    <div class="jumborton">
        <h4 class="mt-3">{% translate "RulesRegulationsHeading" %}</h4>
        <hr>
        <p class="lead">
            {% translate "MainRulesRegulationsText" %}
        </p>
    </div>
{% endblock content %}